### PR TITLE
Milestone 7: Building Responsive Design Using Bootstrap

### PR DESCRIPTION
**Pull request by rajkumardas2701**
This project is built using Bootstrap classes and is a replica of Newsweek page.
=> In this project, we have used Bootstrap classes to add responsiveness to the page in addition to HTML and CSS to give basic structure.
=> Please find Demo link in the readme section of feature branch to see website in different browser resolutions.

### CODE REVIEW

**Review by men32z — COMMENTED** [review]
## Pull request currently under review by Luis Preza (TSE).

Kindly exercise patience 🐱

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @rajkumardas2701 !
## what a great project! 👍
you really did a great job here, good job with bootstrap, your project is responsive, and it consider the breakpoints, your readme is descriptive, and you paid attention to detail. 

There are still some changes 👇 you need to implement to approve this request 🔍
remember that this is a clone page and should be as closest as possible to the original one.
this review was made in Firefox browser, consider support at least Chrome and Firefox.

#### take a look in this screenshot
- [ ] [OPTIONAL] try to match the width of the sponsored insight, in some point between the wide and the mid size, seems to be more space on the left.
Annotation 2020-04-17 184709

#### take a look in this screenshot yours is the left one.
Annotation 2020-04-17 184909
- [x] [ REQUIRED] in mid screens the size of this newsletter container is different.
- [x] [ REQUIRED] color of the buttons and NEWSLETTER title are different. 


#### take a look in this screenshot
Annotation 2020-04-17 184934
- [ ] [ OPTIONAL] you are repeating a lot of articles, i think to save space or images, consider change repeated images titles and descriptions so the site looks less like a template.

#### take a look in this screenshot yours is the left one
Annotation 2020-04-17 185048
your navbar is almost perfect, lets make it in mobile versions.
- [x] [ REQUIRED] hamburger icon has another color (less white).
- [x] [ REQUIRED] subscribe button doesn't have the arrow in mobile. 
- [ ] [ OPTIONAL] the weather info is not in the mobile version( this is up to you, I think looks better the way you have it even when is not in the original page.)

#### take a look in this screenshot yours is the left one
Annotation 2020-04-17 185151
- [x] [REQUIRED] in mobile version when text is more than the height of the image the text goes down the image instead.

#### take a look in this screenshot yours is the left one
Annotation 2020-04-17 185308
- [x] [REQUIRED] there is a space betwen the main content and the footer.
- [x] [REQUIRED] logo seems to be smaller in mobile versions
- [x] [REQUIRED] the "|" separators shouldn't be in the small version.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! :hammer:

--Luis Preza

## Status Request changes

**Comment by rajkumardas2701** [comment]
Hi @men32z ,

Thank you for providing your valuable feedback.
I've implemented necessary changes and request you to please let me know if any further changes required.

Regards,
Rajkumar Das

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @rajkumardas2701! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by rajkumardas2701** [comment]
Hi @christianotieno 

Thank you for your feedback :)

Regards,
Rajkumar Das

**Pull request merged**
